"""add title to snippet

Revision ID: 51ccf2736c6a
Revises: 1f3343b9a4d3
Create Date: 2021-12-23 12:50:57.358939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ccf2736c6a'
down_revision = '1f3343b9a4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snip', sa.Column('title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snip', 'title')
    # ### end Alembic commands ###
